export const CATEGORIES = [
  { id: "general",       label: "World",         icon: "🌍", guardian: "world",              ytq: "world news today" },
  { id: "technology",    label: "Technology",    icon: "💻", guardian: "technology",         ytq: "technology news" },
  { id: "business",      label: "Business",      icon: "📈", guardian: "business",           ytq: "business finance news" },
  { id: "health",        label: "Health",        icon: "🏥", guardian: "healthcare-network", ytq: "health medical news" },
  { id: "sports",        label: "Sports",        icon: "⚽", guardian: "sport",              ytq: "sports news highlights" },
  { id: "entertainment", label: "Culture",       icon: "🎬", guardian: "culture",            ytq: "entertainment culture news" },
  { id: "science",       label: "Science",       icon: "🔬", guardian: "science",            ytq: "science discovery news" },
  { id: "politics",      label: "Politics",      icon: "🏛️", guardian: "politics",           ytq: "politics news analysis" },
];

export const LANGUAGES = [
  { code: "en", name: "English",    flag: "🇬🇧", yt: "en",      sr: "en-US", dir: "ltr" },
  { code: "hi", name: "हिंदी",      flag: "🇮🇳", yt: "hi",      sr: "hi-IN", dir: "ltr" },
  { code: "es", name: "Español",    flag: "🇪🇸", yt: "es",      sr: "es-ES", dir: "ltr" },
  { code: "fr", name: "Français",   flag: "🇫🇷", yt: "fr",      sr: "fr-FR", dir: "ltr" },
  { code: "ar", name: "العربية",    flag: "🇸🇦", yt: "ar",      sr: "ar-SA", dir: "rtl" },
  { code: "zh", name: "中文",       flag: "🇨🇳", yt: "zh-Hans", sr: "zh-CN", dir: "ltr" },
  { code: "de", name: "Deutsch",    flag: "🇩🇪", yt: "de",      sr: "de-DE", dir: "ltr" },
  { code: "pt", name: "Português",  flag: "🇧🇷", yt: "pt",      sr: "pt-BR", dir: "ltr" },
  { code: "ja", name: "日本語",     flag: "🇯🇵", yt: "ja",      sr: "ja-JP", dir: "ltr" },
  { code: "ko", name: "한국어",     flag: "🇰🇷", yt: "ko",      sr: "ko-KR", dir: "ltr" },
  { code: "ru", name: "Русский",    flag: "🇷🇺", yt: "ru",      sr: "ru-RU", dir: "ltr" },
  { code: "it", name: "Italiano",   flag: "🇮🇹", yt: "it",      sr: "it-IT", dir: "ltr" },
];

export const UI = {
  en: { search: "Search world news, topics, people...", latest: "Latest Stories", videos: "Watch Now", readMore: "Read Full Story", breaking: "BREAKING", trending: "Trending", bookmarks: "Saved", noNews: "No stories found", noVideos: "No videos found", saved: "Saved to bookmarks", unsaved: "Removed from saved", copied: "Link copied!", readTime: "min read", darkMode: "Dark mode", lightMode: "Light mode", viewAll: "View All", close: "Close", share: "Share", save: "Save", like: "Like", reader: "Reader View", loading: "Loading..." },
  hi: { search: "विश्व समाचार खोजें...", latest: "ताज़ा खबरें", videos: "अभी देखें", readMore: "पूरी खबर पढ़ें", breaking: "ब्रेकिंग", trending: "ट्रेंडिंग", bookmarks: "सहेजे गए", noNews: "कोई खबर नहीं", noVideos: "कोई वीडियो नहीं", saved: "सहेजा गया", unsaved: "हटाया गया", copied: "लिंक कॉपी!", readTime: "मिनट पढ़ें", darkMode: "डार्क मोड", lightMode: "लाइट मोड", viewAll: "सभी देखें", close: "बंद करें", share: "शेयर", save: "सहेजें", like: "पसंद", reader: "रीडर व्यू", loading: "लोड हो रहा है..." },
  es: { search: "Buscar noticias mundiales...", latest: "Últimas Noticias", videos: "Ver Ahora", readMore: "Leer Historia", breaking: "URGENTE", trending: "Tendencias", bookmarks: "Guardados", noNews: "Sin resultados", noVideos: "Sin videos", saved: "Guardado", unsaved: "Eliminado", copied: "Enlace copiado", readTime: "min leer", darkMode: "Modo oscuro", lightMode: "Modo claro", viewAll: "Ver todos", close: "Cerrar", share: "Compartir", save: "Guardar", like: "Me gusta", reader: "Vista lectura", loading: "Cargando..." },
  fr: { search: "Rechercher des actualités...", latest: "Dernières Nouvelles", videos: "Regarder", readMore: "Lire la Suite", breaking: "URGENT", trending: "Tendances", bookmarks: "Sauvegardés", noNews: "Aucun résultat", noVideos: "Aucune vidéo", saved: "Sauvegardé", unsaved: "Supprimé", copied: "Lien copié", readTime: "min lecture", darkMode: "Mode sombre", lightMode: "Mode clair", viewAll: "Voir tout", close: "Fermer", share: "Partager", save: "Sauvegarder", like: "Aimer", reader: "Mode lecture", loading: "Chargement..." },
  ar: { search: "البحث في أخبار العالم...", latest: "آخر الأخبار", videos: "شاهد الآن", readMore: "اقرأ القصة كاملة", breaking: "عاجل", trending: "الأكثر تداولا", bookmarks: "المحفوظات", noNews: "لا توجد نتائج", noVideos: "لا توجد فيديوهات", saved: "تم الحفظ", unsaved: "تمت الإزالة", copied: "تم نسخ الرابط", readTime: "دقيقة قراءة", darkMode: "الوضع الداكن", lightMode: "الوضع الفاتح", viewAll: "عرض الكل", close: "إغلاق", share: "مشاركة", save: "حفظ", like: "إعجاب", reader: "وضع القراءة", loading: "جار التحميل..." },
  zh: { search: "搜索全球新闻...", latest: "最新报道", videos: "立即观看", readMore: "阅读全文", breaking: "突发新闻", trending: "热门话题", bookmarks: "已收藏", noNews: "未找到内容", noVideos: "未找到视频", saved: "已保存", unsaved: "已移除", copied: "链接已复制", readTime: "分钟阅读", darkMode: "深色模式", lightMode: "浅色模式", viewAll: "查看全部", close: "关闭", share: "分享", save: "保存", like: "点赞", reader: "阅读视图", loading: "加载中..." },
  de: { search: "Weltnachrichten suchen...", latest: "Aktuelle Nachrichten", videos: "Jetzt ansehen", readMore: "Ganzen Artikel lesen", breaking: "EILMELDUNG", trending: "Trending", bookmarks: "Gespeichert", noNews: "Keine Ergebnisse", noVideos: "Keine Videos", saved: "Gespeichert", unsaved: "Entfernt", copied: "Link kopiert", readTime: "Min lesen", darkMode: "Dunkelmodus", lightMode: "Hellmodus", viewAll: "Alle ansehen", close: "Schließen", share: "Teilen", save: "Speichern", like: "Gefällt mir", reader: "Lesemodus", loading: "Laden..." },
  pt: { search: "Pesquisar noticias mundiais...", latest: "Ultimas Noticias", videos: "Assistir Agora", readMore: "Ler Historia Completa", breaking: "URGENTE", trending: "Em Alta", bookmarks: "Salvos", noNews: "Sem resultados", noVideos: "Sem videos", saved: "Salvo", unsaved: "Removido", copied: "Link copiado", readTime: "min ler", darkMode: "Modo escuro", lightMode: "Modo claro", viewAll: "Ver tudo", close: "Fechar", share: "Compartilhar", save: "Salvar", like: "Curtir", reader: "Modo leitura", loading: "Carregando..." },
  ja: { search: "世界のニュースを検索...", latest: "最新ニュース", videos: "今すぐ視聴", readMore: "全文を読む", breaking: "速報", trending: "トレンド", bookmarks: "保存済み", noNews: "結果なし", noVideos: "動画なし", saved: "保存しました", unsaved: "削除しました", copied: "リンクをコピー", readTime: "分で読む", darkMode: "ダークモード", lightMode: "ライトモード", viewAll: "すべて表示", close: "閉じる", share: "共有", save: "保存", like: "いいね", reader: "リーダービュー", loading: "読み込み中..." },
  ko: { search: "세계 뉴스 검색...", latest: "최신 뉴스", videos: "지금 시청", readMore: "전체 기사 보기", breaking: "속보", trending: "트렌딩", bookmarks: "저장됨", noNews: "결과 없음", noVideos: "동영상 없음", saved: "저장됨", unsaved: "제거됨", copied: "링크 복사됨", readTime: "분 읽기", darkMode: "다크 모드", lightMode: "라이트 모드", viewAll: "전체 보기", close: "닫기", share: "공유", save: "저장", like: "좋아요", reader: "독자 보기", loading: "로딩 중..." },
  ru: { search: "Поиск мировых новостей...", latest: "Последние новости", videos: "Смотреть сейчас", readMore: "Читать полностью", breaking: "СРОЧНО", trending: "В тренде", bookmarks: "Сохранено", noNews: "Результатов нет", noVideos: "Видео нет", saved: "Сохранено", unsaved: "Удалено", copied: "Ссылка скопирована", readTime: "мин чтения", darkMode: "Тёмная тема", lightMode: "Светлая тема", viewAll: "Смотреть все", close: "Закрыть", share: "Поделиться", save: "Сохранить", like: "Нравится", reader: "Режим чтения", loading: "Загрузка..." },
  it: { search: "Cerca notizie mondiali...", latest: "Ultime Notizie", videos: "Guarda Ora", readMore: "Leggi la storia", breaking: "URGENTE", trending: "Tendenze", bookmarks: "Salvati", noNews: "Nessun risultato", noVideos: "Nessun video", saved: "Salvato", unsaved: "Rimosso", copied: "Link copiato", readTime: "min lettura", darkMode: "Modalita scura", lightMode: "Modalita chiara", viewAll: "Vedi tutto", close: "Chiudi", share: "Condividi", save: "Salva", like: "Mi piace", reader: "Modalita lettura", loading: "Caricamento..." },
};

export const YT_KEY  = (typeof import.meta !== "undefined" && import.meta.env) ? (import.meta.env.VITE_YOUTUBE_API_KEY || "") : "";
export const YT_BASE = "https://www.googleapis.com/youtube/v3";

export const TRENDING = ["Climate Summit 2026", "AI Breakthrough", "World Cup 2026", "Space Mission", "Global Economy", "Tech Giants", "Health Research", "Crypto Markets"];
